packages:
  - packages/*
  - packages/desktop/*
  - packages/shared/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - electron
  - prisma
  - sharp
  - sqlite3
  - unrs-resolver
